photo_ids = {
    'main_bot': {
        'win_game': 'AgACAgIAAxkBAAIC2WTqMiFdkFEDiIBss28tBRMOmr3iAAJfzjEbLQNRS_pj3mg6HMiwAQADAgADcwADMAQ',
        'loose_game': 'AgACAgIAAxkBAAIC7mTqNXXEfWJ5rEOXYVfG7PVcPMbOAALj0DEb6x5RS5-dRhC_9KTKAQADAgADcwADMAQ',
        'rama': 'AgACAgIAAxkBAAIC-GTqNptVlDX46YdnD0uPYfE2NQfdAALy0DEb6x5RSyZrdUNdmTP_AQADAgADcwADMAQ',
        'clown': 'AgACAgIAAxkBAAIDAAFk6jcjaN6p23sOuQN3adbypnYrVwAC6dAxG-seUUuUm9-jS7VgMgEAAwIAA3MAAzAE',
        'dura': ['AgACAgIAAxkBAAIDAAFk6jcjaN6p23sOuQN3adbypnYrVwAC6dAxG-seUUuUm9-jS7VgMgEAAwIAA3MAAzAE', 'AgACAgIAAxkBAAIDBmTqN5DcLIMd0D57A0vFWb_XLStZAALr0DEb6x5RSyHLdhK8J_fxAQADAgADcwADMAQ'],
        'squirrel': 'AgACAgIAAxkBAAIDDGTqOBLpsI8gfMKlK-resEh8by_8AAL20DEb6x5RS3Uj6sSt_eudAQADAgADcwADMAQ',
        'ibragym_images': ['AgACAgIAAxkBAAIDE2TqOLJH7APzjrOT9bCGQpKugvRyAAL30DEb6x5RS5KaZdMT_CzsAQADAgADcwADMAQ', 'AgACAgIAAxkBAAIDFWTqOLeVs2Qjq8H7Hq-vZBBrFb1EAAL40DEb6x5RSzNBIVJa6CUnAQADAgADcwADMAQ', 'AgACAgIAAxkBAAIDF2TqOMAwAQX0Y146TIHgsHCLAXS4AAL50DEb6x5RS5t1pINk5CjvAQADAgADcwADMAQ'],
        'medusa': 'AgACAgIAAxkBAAIDLWTqOrk78tfnD-NoKMfeseni2keKAAL10DEb6x5RS7gwqT8K9JXnAQADAgADcwADMAQ',
        'marathon': 'AgACAgIAAxkBAAIDKGTqOmn9yj4-kuub06KH3koBWIX8AAL00DEb6x5RS0lDMjfgBQKPAQADAgADcwADMAQ'
    },
    'test_bot': {
        'win_game': 'AgACAgIAAxkDAAIGZGTqJLIDX22vPwABduYLR8b1vZvQrgAClssxGw8uQUuOSnCweNGOBgEAAwIAA3MAAzAE',
        'loose_game': 'AgACAgIAAxkDAAIGb2TqJ4er20mgVZ1ppTjFQwYCk3OHAALj0DEb6x5RSzuzcTKdWwpBAQADAgADcwADMAQ',
        'rama': 'AgACAgIAAxkDAAIGhmTqKVYAASg13SzJQx2K3Jq1bTB2VgAC8tAxG-seUUuY_kr72WW8YQEAAwIAA3MAAzAE',
        'clown': 'AgACAgIAAxkDAAIGd2TqKDlyyvSjxvc2X61T3xDs8KRWAALp0DEb6x5RS8l2f--imoymAQADAgADcwADMAQ',
        'dura': ['AgACAgIAAxkDAAIGe2TqKJvzQmtW0zgu2lXWQnsp0EntAALr0DEb6x5RS3rG5H9D0t5aAQADAgADcwADMAQ', 'AgACAgIAAxkDAAIGd2TqKDlyyvSjxvc2X61T3xDs8KRWAALp0DEb6x5RS8l2f--imoymAQADAgADcwADMAQ'],
        'squirrel': 'AgACAgIAAxkDAAIGmWTqKkSm1T9A-8TrnlBSfD2yOhWAAAL20DEb6x5RS4hVGetdDlD1AQADAgADcwADMAQ',
        'ibragym_images': ['AgACAgIAAxkDAAIGnGTqKsH8nQqsXbewfgg8SjiwqWrCAAL30DEb6x5RS12Zy_xipJpuAQADAgADcwADMAQ', 'AgACAgIAAxkDAAIGnmTqKtJI1G4n0lBjP8aMNa1ozZGvAAL40DEb6x5RS2NqgtLDqWEuAQADAgADcwADMAQ', 'AgACAgIAAxkDAAIGoGTqKunTA7wLRld7nuZjGWjnwm7NAAL50DEb6x5RS_Ljy64XejF0AQADAgADcwADMAQ'],
        'medusa': 'AgACAgIAAxkDAAIGk2TqKfsZiL9jN9vXEUJd3JpECeaYAAL10DEb6x5RS0c43nPHIAiRAQADAgADcwADMAQ',
        'marathon': 'AgACAgIAAxkDAAIGi2TqKaBX7E-Hrzd6DjJsoG-ZR5E9AAL00DEb6x5RS-_BR15sVVV0AQADAgADcwADMAQ'
    }
}