sticker_ids = {
    'pay': 'CAACAgIAAxkBAAEBLThizZnIHTLfN24LodNlBXYilqcoNQAC-w8AArGreUvmmZ8F9DW_NSkE',
    'go_home': 'CAACAgIAAxkBAAEFPvNizFgQ9nKuLwGp_kaDdp9DI2VpLgACERQAAqAAAehLhynfNnamXaEpBA',
    'ronaldo': 'CAACAgIAAxkBAAEd7T5kAjns3pTDTQ0zcyI6rkvEY1-lUAAC6w8AAgGi2Ev5tLQa4TvsLy4E',
    'mr_incredible': {
        0: 'CAACAgIAAxkBAAEcvXRj3MBUHblwRlyzN5iPXNaskLXq3QAC2RMAAlJR8Up2MsUL6mQC8C4E',
        1: 'CAACAgIAAxkBAAEcvXZj3MCeoUyBNliTDGh0PjH1WPdkTgAC0hQAApML-ErVMY8HmlrMQC4E',
        2: 'CAACAgIAAxkBAAEcvXpj3MDCo4Qq9UBpeagvPk_y4ANOpQACXBEAAkqQ-UpaSXqrBf7CSC4E',
        3: 'CAACAgIAAxkBAAEcvX1j3MDQsBU5Z0tcMukIfss6qbAiqQACahAAAjrb-EqZyZ-bRAu4PC4E',
        4: 'CAACAgIAAxkBAAEcvX9j3MDaAAFTYvYTePUU8s6KpUseGGIAArwSAAJOJ_hKURGxjGV7jU0uBA',
        5: 'CAACAgIAAxkBAAEcvYFj3MDbRbmAIpjRudhnkVzY8jDKkAAC2RAAAhX38ErxrB7zMOPdQi4E',
        6: 'CAACAgIAAxkBAAEcvYNj3MDoFElOR7FVmN8ix6DC0PYE6QACbBoAAj018EouHtLtCFVkYS4E'
    }
}
